// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8HGNcyqlTdWbUGlmZhI1iaA5UtS9RNG4',
    appId: '1:704385165707:web:4ee67a89002de027a2e78e',
    messagingSenderId: '704385165707',
    projectId: 'travel-agency-82655',
    authDomain: 'travel-agency-82655.firebaseapp.com',
    storageBucket: 'travel-agency-82655.appspot.com',
    measurementId: 'G-EWSW1YW4MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXrLofkydiydt-DdzvGnakjxGHtLznud4',
    appId: '1:704385165707:android:f360d28cfcfea8aaa2e78e',
    messagingSenderId: '704385165707',
    projectId: 'travel-agency-82655',
    storageBucket: 'travel-agency-82655.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBMHMLmwmtBMCHp3FS0GTFwa87_jLdT8',
    appId: '1:704385165707:ios:136037dc7257f5c6a2e78e',
    messagingSenderId: '704385165707',
    projectId: 'travel-agency-82655',
    storageBucket: 'travel-agency-82655.appspot.com',
    iosBundleId: 'com.example.fabTechSol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBMHMLmwmtBMCHp3FS0GTFwa87_jLdT8',
    appId: '1:704385165707:ios:136037dc7257f5c6a2e78e',
    messagingSenderId: '704385165707',
    projectId: 'travel-agency-82655',
    storageBucket: 'travel-agency-82655.appspot.com',
    iosBundleId: 'com.example.fabTechSol',
  );
}
