// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgxSPZ__Y2G_BgLFR9HiSl_vlt0Hf5i-o',
    appId: '1:187182098550:web:496614204e7fb9ced89757',
    messagingSenderId: '187182098550',
    projectId: 'travel-agency-11fbf',
    authDomain: 'travel-agency-11fbf.firebaseapp.com',
    storageBucket: 'travel-agency-11fbf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAODf74zmbrtL5mdqBOjTcgLIHEwafHW3s',
    appId: '1:187182098550:android:48a7a52909b024f1d89757',
    messagingSenderId: '187182098550',
    projectId: 'travel-agency-11fbf',
    storageBucket: 'travel-agency-11fbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA68sDsj5W-9FJiVnehEEuW0HtxHdn1Aw',
    appId: '1:187182098550:ios:34720f8b7621cdc4d89757',
    messagingSenderId: '187182098550',
    projectId: 'travel-agency-11fbf',
    storageBucket: 'travel-agency-11fbf.appspot.com',
    iosBundleId: 'com.example.fabTechSol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA68sDsj5W-9FJiVnehEEuW0HtxHdn1Aw',
    appId: '1:187182098550:ios:34720f8b7621cdc4d89757',
    messagingSenderId: '187182098550',
    projectId: 'travel-agency-11fbf',
    storageBucket: 'travel-agency-11fbf.appspot.com',
    iosBundleId: 'com.example.fabTechSol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgxSPZ__Y2G_BgLFR9HiSl_vlt0Hf5i-o',
    appId: '1:187182098550:web:efdc0257955c8d03d89757',
    messagingSenderId: '187182098550',
    projectId: 'travel-agency-11fbf',
    authDomain: 'travel-agency-11fbf.firebaseapp.com',
    storageBucket: 'travel-agency-11fbf.appspot.com',
  );

}